# Generated by Django 5.1.7 on 2025-03-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_author_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('announcement', 'Announcement'), ('news', 'News')], default='blog', max_length=20),
        ),
    ]
