# Generated by Django 5.1.7 on 2025-03-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_metadata_remove_post_post_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('announcement', 'Announcement'), ('image', 'Image'), ('video', 'Video')], default='blog', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='untitled', max_length=255),
            preserve_default=False,
        ),
    ]
